all:
  children:
    production:
      hosts:
        tulln-prod-app:
          ansible_host: 1.2.3.4
          ansible_user: root
          private_ip: 10.0.1.20
        tulln-prod-db:
          ansible_host: 1.2.3.5
          ansible_user: root
          private_ip: 10.0.1.10

    app:
      hosts:
        tulln-prod-app:

    data:
      hosts:
        tulln-prod-db:

    monitoring:
      hosts:
        tulln-prod-db:

  vars:
    tulln_env: production
    project_name: tulln
    db_host: 10.0.1.10
    db_port: 5432
    app_port: 4000
    prometheus_port: 9090
    grafana_port: 3000
    monitoring_enabled: true
