[app]
; replace with the tulln-data app host(s)
178.105.161.12

[data]
; replace with the tulln-data database host(s)
178.105.161.12

[monitoring]
; replace with the tulln-data monitoring host
178.105.161.12
