---
- name: caddy | Install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
  tags: ["caddy"]

- name: caddy | Apt keys
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
  tags: ["caddy"]

- name: caddy | Run apt update
  apt: update_cache=yes
  tags: ["caddy"]

- name: caddy | Run install caddy
  apt: name=caddy
  tags: ["caddy"]

- name: caddy | Copy Caddyfile
  template: src=Caddyfile.j2 dest=/etc/caddy/Caddyfile
  tags: ["caddy"]
  notify: Restart caddy
